# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Workout Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workout Tracker
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.4.1'
  pod 'SwiftLint'

end
